config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :lists, only: [:new, :create, :show, :index, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: {minimum: 6}
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[show destroy]

  def show
  end

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
    redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity

    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private
  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def edit
    # @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to list_url(@list), notice: "List was successfully created." }

      else
        format.html { render :new, status: :unprocessable_entity }

      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to list_url(@list), notice: "List was successfully updated." }

      else
        format.html { render :edit, status: :unprocessable_entity }

      end
    end
  end

  def destroy
    @list.destroy!

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
    end
  end

  private

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show ]

  def index
    @movies = Movie.all
  end

  def show
  end

  # def new
  #   @movie = Movie.new
  # end

  # def edit
  # end

  # def create
  #   @movie = Movie.new(movie_params)

  #   respond_to do |format|
  #     if @movie.save
  #       format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }

  #     else
  #       format.html { render :new, status: :unprocessable_entity }

  #     end
  #   end
  # end

  # def update
  #   respond_to do |format|
  #     if @movie.update(movie_params)
  #       format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }

  #     else
  #       format.html { render :edit, status: :unprocessable_entity }

  #     end
  #   end
  # end

  # def destroy
  #   @movie.destroy!

  #   respond_to do |format|
  #     format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
  #   end
  # end

  private

    def set_movie
      @movie = Movie.find(params[:id])
    end


    def movie_params
      params.require(:movie).permit(:title, :overview, :poster_url, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.collection_select :movie_id, Movie.order(:title), :id, :title %>
    <%= f.input :list %>
    <%= f.input :comment %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-outline-light" %>
  </div>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container">
<h1>Add list</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :movie_id, collection: Movie.all %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>
<%= link_to "Back to lists ?", lists_path, class:"btn btn-outline-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-outline-light" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="container">
<div id="<%= dom_id list %>">
  <p>
    <strong>Name:</strong>
    <%= list.name %>
  </p>

</div>
</div>

app/views/lists/edit.html.erb
<div class="container">
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list, class:"btn btn-outline-info" %> |
  <%= link_to "Back to lists", lists_path, class:"btn btn-outline-primary" %>
</div>
</div>

app/views/lists/index.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>

<h1>Lists</h1>
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://cdn.pixabay.com/photo/2012/04/13/12/25/polaroid-32180_1280.png)">
<div id="lists">
  <% @lists.each do |list| %>
    <%= render list %>
    </div>
    </div>
    <p>
      <%= link_to "Show this list", list, class:"btn btn-outline-info" %>
      <%= link_to "Delete this list", list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure ?"}, class:"btn btn-outline-danger" %>
    </p>
  <% end %>
</div>
    <%= link_to "New list", new_list_path, class:"btn btn-outline-success" %>
<%= link_to "Back to the movies", movies_path, class:"btn btn-outline-primary" %>
</div>

app/views/lists/new.html.erb
<div class="container">
<h1>New list</h1>
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://cdn.pixabay.com/photo/2012/04/13/12/25/polaroid-32180_1280.png)">
<%= render "form", list: @list %>
</div>
    </div>
<br>

<div>
  <%= link_to "Back to lists", lists_path, class:"btn btn-outline-primary" %>
</div>
</div>

app/views/lists/show.html.erb
<div class="container">
<h2><%= @list.name %></h2>
<ul>
<% @list.bookmarks.each do |bookmark| %>
<li> <%= bookmark.movie.title %></li>
<li><%= bookmark.movie.rating %></li>
<li><%= bookmark.movie.overview %></li>
<li><%= bookmark.comment %></li>
 <%= link_to "Delete this movie", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure ?"}, class:"btn btn-outline-danger"  %>
<% end %>
</ul>
<%= link_to "Back to lists ?", lists_path, class:"btn btn-outline-primary" %>
<%= link_to "Add movies to the lists ?", new_list_bookmark_path(@list), class:"btn btn-outline-success" %>
</div>

app/views/movies/_movie.html.erb
<div class="container">
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Overview:</strong>
    <%= movie.overview %>
  </p>

  <p>
    <strong>Poster url:</strong>
    <%= movie.poster_url %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating %>
  </p>

</div>
</div>

app/views/movies/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.freepik.com/vecteurs-libre/bande-film-fond-cinema-effet-lumiere_1017-38171.jpg?w=1380&t=st=1708698351~exp=1708698951~hmac=20eaab574fa9678b4c31fa031b8114f59af8bc5ea728d0a56328181769587d0f);">

     <h1><strong>Movie</strong></h1>
    <p>Change your life and see all movies in the world.</p>
  </div>
</div>

<div class="container">
  <div id="movies">
    <% @movies.each do |movie| %>
      <div class="card">
        <img class="card-img-top" src="<%= movie.poster_url %>" alt="<%= movie.title %>">
        <div class="card-body">
          <h5 class="card-title"><%= movie.title %></h5>
          <p class="card-text"><%= movie.overview  %></p>
        </div>
      </div>
      <p>
        <%= link_to "Show this movie", movie, class:"btn btn-outline-info" %>
      </p>
    <% end %>
  </div>

  <%= link_to "Go to your lists", lists_path, class:"btn btn-outline-primary" %>
</div>

app/views/movies/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="card">
    <img class="card-img-top" src="<%= @movie.poster_url %>" alt="<%= @movie.title %>">
    <div class="card-body">
      <h5 class="card-title"><%= @movie.title %></h5>
      <p class="card-text"><%= @movie.overview %></p>
    </div>
  </div>

  <p>
    <%= link_to "Back to movies", movies_path, class:"btn btn-outline-primary" %>
  </p>
</div>